WEBSOCKET ws://localhost:80/websocket
Content-Type: application/json // used only for IDE highlighting.
// Highlighting is applied for each message independently.


{
    "message": "Send when the WebSocket connection is opened"
}
=== wait-for-server
{
    "message": "Wait for the tests message and send the current message as response"
}
===
{
    "message": "Send after previous message without waiting for the tests message"
}

###
POST http://localhost:80/api/item
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="field-name"

field-value
--WebAppBoundary--

###

POST http://localhost:80/api/item
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###

POST http://localhost:80/api/item
Content-Type: application/json

{}

###

###

GET http://localhost:8080/api/issue/token
Accept: application/json
Refresh_Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ3b25iaW5AbWFpbC5jb20iLCJleHAiOjE2NjU2Nzk1OTcsImlhdCI6MTY2NTY2OTU5N30.VrAbI37jKCzlkDP8xGWVZq3aL8qwao9OZSFs-mMzz4s

###
POST http://localhost:8080/api/account
Content-Type: application/json

{
  "email": "wonbin@mail.com",
  "password": "bin1234"
}

###
POST http://localhost:8080/api/account/signup
Content-Type: application/json

{
  "email": "wonbin@mail.com",
  "password": "bin1234",
  "phoneNumber": "01033332222"
}

###