package com.example.speedsideproject.post.enums;

public enum Tech {
    JAVASCRIPT, TYPESCRIPT, REACT, VUE, NODEJS, SPRING, JAVA, NEXTJS, NESTJS, EXPRESS, GO, C,
    PYTHON, DJANGO, SWIFT, KOTLIN, MYSQL, MONGODB, PHP, GRAPHQL, FIREBASE, REACTNATIVE,
    UNITY, FLUTTER, AWS, KUBERNETES, DOCKER, GIT, FIGMA, ZEPLIN
}
