package com.example.speedsideproject.domain.post.enums;

public enum Tech {
//    JAVASCRIPT, TYPESCRIPT, REACT, VUE, NODEJS, SPRING, JAVA, NEXTJS, NESTJS, EXPRESS, GO, C,
//    PYTHON, DJANGO, SWIFT, KOTLIN, MYSQL, MONGODB, PHP, GRAPHQL, FIREBASE, REACTNATIVE,
//    UNITY, FLUTTER, AWS, KUBERNETES, DOCKER, ZEPLIN, CPP, CS, SVELTE,

    FIGMA,SLACK,GITHUB,ZIRA,DISCORD, NOTION,ZEPLIN,

    JAVASCRIPT,TYPESCRIPT,REACT,VUE,SVELTE,NEXTJS,

    NODEJS,SPRING,JAVA,EXPRESS,GO,PYTHON,DJANGO,MYSQL,MONGODB,PHP,GRAPHQL,FIREBASE,

    KOTLIN,SWIFT,REQCTNATIVE,FLUTTER,UNITY,

}
